# Condemned2Recomp Functions (Title Update Version)

[functions]
0x82201590 = {}
0x82841168 = {}
0x8284DEE8 = {}
0x8221D638 = {}
0x821B5230 = {}
0x828465B8 = {}
0x82850880 = {}
0x822656E8 = {}
0x822418E0 = {}
0x822782A0 = {}
0x8221A2C0 = {}
0x821B5FE0 = {}
0x822418D0 = {}
0x821B5248 = {}
0x82265640 = {}
0x8221A2A0 = {}
0x821F8068 = {}
0x82183788 = {}
0x821F4A78 = {}
0x821F8090 = {}
0x821C5FD8 = {}
0x821B5270 = {}
0x821A0C20 = {}
0x82600600 = {}
0x821C5AF0 = {}
0x821DA968 = {}
0x821F4A38 = {}
0x82694D08 = {}
0x824DA6B8 = {}
0x82123768 = {}
0x8220BAF0 = {}

########################
# Condemned2 Functions #
########################
# Console
0x826A7E90 = {name="SetFloatCVar"}
0x826A7C60 = {name="GetFloatCVar"}
0x826A7D78 = {name="SetIntCvar"}
0x826A7AC0 = {name="GetBoolCvar"}
0x82175C58 = {name="SetConfigCvar"}

# Config/Init
0x824262C8 = {name="Player_UserSettings"}
0x823C76A8 = {name="Player_ApplySettings"} 
0x82221E40 = {name="ParseSWF"}

# Level of Detail
0x8212A400 = {name="ApplyDisplaySettings"}
0x8237A218 = {name="Global_ShadowLOD"}
0x8247F668 = {name="Global_MinShadowLOD"}

# Graphics
0x8212A4D8 = {name="InitializeDisplay"}
0x82129C38 = {name="InitializeVideo"}
0x82133538 = {name="InitializeMaterialsShaders"}
0x8265E980 = {name="InitializeBatch"}

# Video Display
0x828C8D54 = {name="VdSwap"}
0x828C8D64 = {name="VdGetSystemCommandBuffer"}
0x828C8D44 = {name="VdPersistDisplay"}
0x828C8B54 = {name="MmAllocatePhysicalMemoryEx"}
0x828C8B64 = {name="MmFreePhysicalMemory"}

# Input
0x8234BDC8 = {name="Input_GetAxis"} 
0x8234BE30 = {name="Input_GetButton"}
0x8234C130 = {name="Input_KeyDown"}
0x8234BEC0 = {name="Input_KeyUp"}
0x8234BF28 = {name="Input_KeyHold"}
0x82315438 = {name="Input_PlayerInput"}
0x82425158 = {name="AimingSensitivity"} # Aiming sensitivity setting
0x8230A428 = {name="ProcessLookInput"}
0x82306DE8 = {name="Camera_MouseLook"} # Restored native mouse look!

# Gameplay
0x823D56C0 = {name="TvAntennaAdjust"} # Used to toggle additive mouse input
0x82302DB0 = {name="IsMeleeWeapon"} # Checks if the player has a melee weapon
0x824384F0 = {name="BodyCapFunction"} # Body capsule physics
0x826A5508 = {name="OnAttackEffect"} # Seems to be involved in whether there's gore or just a decal.
0x82325C08 = {name="Game_BundleLoad"} # Loads various assets

# Misc
0x82561760 = {name="Math_ApplyLinearCurve"} # This has various applications, such as input sensitivity and various sfx settings.